CREATE TABLE [DigitalDatamart].[DimDate] (
    [DateKey]                INT           NOT NULL,
    [DateValue]              DATE          NULL,
    [DayOfWeek]              SMALLINT      NULL,
    [DayOfMonth]             SMALLINT      NULL,
    [DayName]                NVARCHAR (9)  NULL,
    [DayAbr]                 CHAR (3)      NULL,
    [IsWeekday]              CHAR (1)      NULL,
    [CalendarYear]           SMALLINT      NULL,
    [CalendarQuarterOfYear]  SMALLINT      NULL,
    [CalendarQuarter]        NVARCHAR (7)  NULL,
    [CalendarMonthOfYear]    INT           NULL,
    [CalendarMonth]          NVARCHAR (9)  NULL,
    [CalendarMonthDisplay]   NVARCHAR (8)  NULL,
    [CalendarMonthName]      NVARCHAR (9)  NULL,
    [CalendarMonthAbr]       CHAR (3)      NULL,
    [CalendarWeekOfYear]     SMALLINT      NULL,
    [CalendarWeek]           NVARCHAR (9)  NULL,
    [FiscalYear]             SMALLINT      NULL,
    [FiscalYearDisplay]      NVARCHAR (12) NULL,
    [FiscalYearDisplayShort] NVARCHAR (12) NULL,
    [FiscalQuarterOfYear]    SMALLINT      NULL,
    [FiscalQuarter]          NVARCHAR (7)  NULL,
    [FiscalPeriodOfYear]     SMALLINT      NULL,
    [FiscalPeriod]           NVARCHAR (8)  NULL,
    [FiscalYearPeriod]       INT           NULL,
    [ETLBatchId]             VARCHAR (128) NULL,
    CONSTRAINT [PK_DimDate] PRIMARY KEY CLUSTERED ([DateKey] ASC)
);

