CREATE TABLE [Staging].[S_CONTACT_LOYX] (
    [ROW_ID]        NVARCHAR (60) NOT NULL,
    [CREATED]       DATETIME      NULL,
    [CREATED_BY]    NVARCHAR (60) NULL,
    [LAST_UPD]      DATETIME      NULL,
    [LAST_UPD_BY]   NVARCHAR (60) NULL,
    [PAR_ROW_ID]    NVARCHAR (60) NULL,
    [PR_SMS_NUM_ID] NVARCHAR (60) NULL,
    [PR_FAX_NUM_ID] NVARCHAR (60) NULL,
    [ETLRunPkgID]   INT           NULL,
    [ETRunStepID]   INT           NULL,
    [CreatedDate]   DATETIME2 (7) NOT NULL,
    [UpdatedDate]   DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_S_CONTACT_LOYX] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);






GO



GO


